window.env = {
  "ALLUSERSPROFILE": "C:\\ProgramData",
  "API_KEY": "bfb2520eea1316d617e6363687d72d8f",
  "APPDATA": "C:\\Users\\samir\\AppData\\Roaming",
  "CHROME_CRASHPAD_PIPE_NAME": "\\\\.\\pipe\\crashpad_21432_YZCKCIELREHFNTKE",
  "COLOR": "1",
  "COLORTERM": "truecolor",
  "CommonProgramFiles": "C:\\Program Files\\Common Files",
  "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
  "CommonProgramW6432": "C:\\Program Files\\Common Files",
  "COMPUTERNAME": "TRAFFY",
  "ComSpec": "C:\\WINDOWS\\system32\\cmd.exe",
  "configsetroot": "C:\\WINDOWS\\ConfigSetRoot",
  "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
  "EDITOR": "C:\\WINDOWS\\notepad.exe",
  "EFC_19936": "1",
  "FPS_BROWSER_APP_PROFILE_STRING": "Internet Explorer",
  "FPS_BROWSER_USER_PROFILE_STRING": "Default",
  "GIT_ASKPASS": "c:\\Users\\samir\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass.sh",
  "HOME": "C:\\Users\\samir",
  "HOMEDRIVE": "C:",
  "HOMEPATH": "\\Users\\samir",
  "INIT_CWD": "C:\\Users\\samir\\Code\\Test\\weather-app",
  "LANG": "en_US.UTF-8",
  "LOCALAPPDATA": "C:\\Users\\samir\\AppData\\Local",
  "LOGONSERVER": "\\\\TRAFFY",
  "NODE": "C:\\Program Files\\nodejs\\node.exe",
  "NODE_EXE": "C:\\Program Files\\nodejs\\\\node.exe",
  "NPM_CLI_JS": "C:\\Program Files\\nodejs\\\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_command": "run-script",
  "npm_config_cache": "C:\\Users\\samir\\AppData\\Local\\npm-cache",
  "npm_config_globalconfig": "C:\\Users\\samir\\AppData\\Roaming\\npm\\etc\\npmrc",
  "npm_config_global_prefix": "C:\\Users\\samir\\AppData\\Roaming\\npm",
  "npm_config_init_module": "C:\\Users\\samir\\.npm-init.js",
  "npm_config_local_prefix": "C:\\Users\\samir\\Code\\Test\\weather-app",
  "npm_config_node_gyp": "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js",
  "npm_config_noproxy": "",
  "npm_config_npm_version": "10.2.3",
  "npm_config_prefix": "C:\\Users\\samir\\AppData\\Roaming\\npm",
  "npm_config_userconfig": "C:\\Users\\samir\\.npmrc",
  "npm_config_user_agent": "npm/10.2.3 node/v20.10.0 win32 x64 workspaces/false",
  "npm_execpath": "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js",
  "npm_lifecycle_event": "deploy",
  "npm_lifecycle_script": "react-dotenv && gh-pages -d build",
  "npm_node_execpath": "C:\\Program Files\\nodejs\\node.exe",
  "npm_package_json": "C:\\Users\\samir\\Code\\Test\\weather-app\\package.json",
  "npm_package_name": "weather-app",
  "npm_package_version": "0.1.0",
  "NPM_PREFIX_NPM_CLI_JS": "C:\\Users\\samir\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js",
  "NUMBER_OF_PROCESSORS": "6",
  "OneDrive": "C:\\Users\\samir\\OneDrive",
  "OneDriveConsumer": "C:\\Users\\samir\\OneDrive",
  "ORIGINAL_XDG_CURRENT_DESKTOP": "undefined",
  "OS": "Windows_NT",
  "Path": "C:\\Users\\samir\\Code\\Test\\weather-app\\node_modules\\.bin;C:\\Users\\samir\\Code\\Test\\node_modules\\.bin;C:\\Users\\samir\\Code\\node_modules\\.bin;C:\\Users\\samir\\node_modules\\.bin;C:\\Users\\node_modules\\.bin;C:\\node_modules\\.bin;C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\@npmcli\\run-script\\lib\\node-gyp-bin;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\Git\\cmd;C:\\Program Files\\nodejs\\;C:\\Users\\samir\\AppData\\Local\\Programs\\Python\\Launcher\\;C:\\Users\\samir\\AppData\\Local\\Microsoft\\WindowsApps;;C:\\Users\\samir\\AppData\\Local\\Programs\\Microsoft VS Code\\bin;C:\\Users\\samir\\AppData\\Roaming\\npm",
  "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
  "PROCESSOR_ARCHITECTURE": "AMD64",
  "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 158 Stepping 10, GenuineIntel",
  "PROCESSOR_LEVEL": "6",
  "PROCESSOR_REVISION": "9e0a",
  "ProgramData": "C:\\ProgramData",
  "ProgramFiles": "C:\\Program Files",
  "ProgramFiles(x86)": "C:\\Program Files (x86)",
  "ProgramW6432": "C:\\Program Files",
  "PROMPT": "$P$G",
  "PSModulePath": "C:\\Users\\samir\\OneDrive\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShell\\Modules;C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules",
  "PUBLIC": "C:\\Users\\Public",
  "SESSIONNAME": "Console",
  "SystemDrive": "C:",
  "SystemRoot": "C:\\WINDOWS",
  "TEMP": "C:\\Users\\samir\\AppData\\Local\\Temp",
  "TERM_PROGRAM": "vscode",
  "TERM_PROGRAM_VERSION": "1.89.1",
  "TMP": "C:\\Users\\samir\\AppData\\Local\\Temp",
  "USERDOMAIN": "TRAFFY",
  "USERDOMAIN_ROAMINGPROFILE": "TRAFFY",
  "USERNAME": "samir",
  "USERPROFILE": "C:\\Users\\samir",
  "VSCODE_GIT_ASKPASS_EXTRA_ARGS": "",
  "VSCODE_GIT_ASKPASS_MAIN": "c:\\Users\\samir\\AppData\\Local\\Programs\\Microsoft VS Code\\resources\\app\\extensions\\git\\dist\\askpass-main.js",
  "VSCODE_GIT_ASKPASS_NODE": "C:\\Users\\samir\\AppData\\Local\\Programs\\Microsoft VS Code\\Code.exe",
  "VSCODE_GIT_IPC_HANDLE": "\\\\.\\pipe\\vscode-git-bb399b49d1-sock",
  "VSCODE_INJECTION": "1",
  "VSCODE_NONCE": "ad6766f0-854b-41ea-8921-cb35d7d70651",
  "windir": "C:\\WINDOWS"
};